### ISSUE TITLE
Workers should not join as manager 

### ISSUE THREAD

**Issue by sanfx** [nmarus/docker-swarm-ansible#1]
I was trying to use your asbible playbook, its very well written but I think you did not cared about joining the worker node, which it works fine with just the managers , if we use worker nodes as well the asible playbook breaks here:

https://github.com/nmarus/docker-swarm-ansible/blob/15d0a499b1e2ce07b25a66c37cbb88cd477f5fbd/playbooks/roles/swarm-workers/tasks/main.yml#L7

You calling the playbook swarm-worker but the task is trying to join the node as manager.
as docker node ls wont work on the worker node.
https://github.com/nmarus/docker-swarm-ansible/blob/15d0a499b1e2ce07b25a66c37cbb88cd477f5fbd/playbooks/roles/swarm-workers/tasks/main.yml#L3

**Comment by patrykbaszak** [comment]
I correct this file in my case:
```
- name: Check if Swarm has already been initialized
  shell: |
      if [ "$(docker info | grep Swarm | sed 's/Swarm: //g')" == "inactive" ]; then
        exit 1;
      else
        echo true;
      fi
  register: swarm_status
  ignore_errors: true
```

**Comment by sanfx** [comment]
Nice work thanks .
